"$schema" = 'https://starship.rs/config-schema.json'

format = """
  [](#5F8CAA)\
$os\
$username\
[](bg:#46484D fg:#5F8CAA)\
$directory\
[](fg:#46484D bg:#3E5889)\
$git_branch\
$git_status\
[](fg:#3E5889 bg:#939CA1)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#939CA1 bg:#5F8CAA)\
$docker_context\
[](fg:#5F8CAA bg:#5F8CAA)\
$time\
[ ](fg:#5F8CAA)\n >> 
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#5F8CAA"
style_root = "bg:#5F8CAA"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#5F8CAA"
disabled = true # Disabled by default

[directory]
style = "bg:#46484D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5F8CAA"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#3E5889"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#3E5889"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#939CA1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5F8CAA"
format = '[ 󰣇 $time ]($style)'
