"$schema" = 'https://starship.rs/config-schema.json'

format = """
 [](#E0586B)\
$os\
$username\
[](bg:#3E3C3E fg:#E0586B)\
$directory\
[](fg:#3E3C3E bg:#4D6B7D)\
$git_branch\
$git_status\
[](fg:#4D6B7D bg:#8A9698)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#8A9698 bg:#E0586B)\
$docker_context\
[](fg:#E0586B bg:#E0586B)\
$time\
[ ](fg:#E0586B)\n >> 
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#E0586B"
style_root = "bg:#E0586B"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#E0586B"
disabled = true # Disabled by default

[directory]
style = "bg:#3E3C3E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#E0586B"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#4D6B7D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4D6B7D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8A9698"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#E0586B"
format = '[ 󰣇 $time ]($style)'
