backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/shared/wallust.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/colors-wallust.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/wallust.conf'
kitty.template = 'kitty.conf'
kitty.target = '~/.config/kitty/wallust.conf'
zsh.template = 'colors-zsh.zsh'
zsh.target = '~/.wallust.zsh'
dynamic-color.template = 'dynamic-color.sh'
dynamic-color.target = '~/.config/scripts/shared/dynamic-color.sh'
mako.template = 'colors-mako'
mako.target = '~/.config/mako/config'
firefox.template = 'colors-firefox.css'
firefox.target = '~/.config/firefox/colors-firefox.css'
userFirefox.template = 'userColors.css'
userFirefox.target = '~/.mozilla/firefox/d2hzuyk2.default-release/chrome/userColor.css'
starship.template = 'starship.toml'
starship.target = '~/.config/starship.toml'